### ISSUE TITLE
Preserving lemma ids

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/merge-idioms#2]
## what exactly is the problem?

currently:
```python
 def __call__(self, doc: Doc) -> Doc:
        # use lowercase version of the doc.
        matches = self.idiom_matcher(doc)
        matches = self.greedily_normalize(matches)
        for vocab_id, start, end in matches:
            # get back the lemma for this match
            # note: matcher has references to the vocab on its own!
            idiom_lemma = self.idiom_matcher.vocab.strings[vocab_id]
            # retokenise
            with doc.retokenize() as retokeniser:
                # try:
                retokeniser.merge(doc[start:end],
                                  # set tag as idiom
                                  # TODO: make sure you give it vocab_id.
                                  # TODO: maybe give it a custom is_idiom attribute?
                                  # how do you do this..?
                                  attrs={'LEMMA': idiom_lemma, 'TAG': 'IDIOM'})
                # except ValueError as ve:
                #     print("pass merging for:" + match_lemma)
                #     pass
        return doc
```

here, each `match` in `matches` already has `vocab_id`. Since a matcher object shares the vocabulary with a language object, the vocabulary of this pipeline already includes all the idioms that have been added with patterns to `idiom_matcher`. Because of this, merging the tokens with `attrs={'LEMMA': idiom_lemma, 'TAG': 'IDIOM'})` only will result in having two `vocab_id`s that point to the same idiom. Worse, one of them is randomly generated every single time the component is executed.

## To-do's
> 8th of Jan
- [x] move all the constants to `hardcoded.py`
- [x] write a failing  for: preserving `vocab_id`
---
> 9th of Jan
- [x]  implementaition for: preserving `vocab_id`
- [x] fix catch-22 test : what's going on there?

**Comment by eubinecto** [comment]
## what exactly is the problem?

currently:
```python
 def __call__(self, doc: Doc) -> Doc:
        # use lowercase version of the doc.
        matches = self.idiom_matcher(doc)
        matches = self.greedily_normalize(matches)
        for vocab_id, start, end in matches:
            # get back the lemma for this match
            # note: matcher has references to the vocab on its own!
            idiom_lemma = self.idiom_matcher.vocab.strings[vocab_id]
            # retokenise
            with doc.retokenize() as retokeniser:
                # try:
                retokeniser.merge(doc[start:end],
                                  # set tag as idiom
                                  # TODO: make sure you give it vocab_id.
                                  # TODO: maybe give it a custom is_idiom attribute?
                                  # how do you do this..?
                                  attrs={'LEMMA': idiom_lemma, 'TAG': 'IDIOM'})
                # except ValueError as ve:
                #     print("pass merging for:" + match_lemma)
                #     pass
        return doc
```

here, each `match` in `matches` already has `vocab_id`. Since a matcher object shares the vocabulary with a language object, the vocabulary of this pipeline already includes all the idioms that have been added with patterns to `idiom_matcher`. Because of this, merging the tokens with `attrs={'LEMMA': idiom_lemma, 'TAG': 'IDIOM'})` only will result in having two `vocab_id`s that point to the same idiom. Worse, one of them is randomly generated every single time the component is executed.

So, how should I fix this?

**Comment by eubinecto** [comment]
## writing tests first
Before we go and find a way how to fix this (probably adding `LEX` key with value as `vocab_id` to `attrs`? ), let's write a test for this first.

**Comment by eubinecto** [comment]
> 10th of Jan 2021 

## How do I register `lemma_id`? 

I have a question. what exactly is the first element of the match tuple? Is that really the id of the lemma? 

here is what's weird:
```python
                                 # giving the lemma as lemma_id, not lemma string, works.
                                  attrs={'LEMMA': lemma_id})

```
even if you register LEMMA with a hash value for lemma, the following test passes:

```python
    def test_greedily_normalize_have_ones_blood_on_ones_hands(self):
        sent_1 = "If she dies, you have her blood on your hands!"
        # later... you have to test for this. should include the case of having the in place of one's
        # sent_1 = "If she dies, you have the blood on your hands!"
        lemmas_1 = self.get_lemmas(sent_1)
        # so, the problem is, this fails.
        self.assertIn("have one's blood on one's hands", lemmas_1)

```
where `get_lemmas(sent_1)` does:
```python
    def get_lemmas(cls, sent: str) -> List[str]:
        """
        returns a string representation of the lemma
        """
        doc = cls.mip(sent)
        return [
            token.lemma_
            for token in doc
        ]
```

this means that `lemma_id` is indeed the lemma_id of the idiom being merged. 

But what's weird is that the following test won't pass:
```python
    # testing for preservation of vocab_id of idioms
    def test_lemma_ids_are_preserved_for_idioms(self):
        # TODO: make this test pass
        sent_1 = "I've got too much on my hands to help."
        sent_2 = "default like it does if you add a new program, " \
                 "but its not the end of the world."
        sent_3 = " but there comes a time when one has to draw a line in the sand."

        lemma_ids_1 = self.get_lemma_ids(sent_1)
        lemma_ids_2 = self.get_lemma_ids(sent_2)
        lemma_ids_3 = self.get_lemma_ids(sent_3)

        # when are these generated though?
        # they are generated when patterns are added.
        # that's why registering LEMMA attribute with lemma_id works.
        # but how do you... change the token?
        # maybe... there is no way? just maybe?
        lemma_id_1 = self.mip.vocab.strings["on my hands"]
        lemma_id_2 = self.mip.vocab.strings["not the end of the world"]
        lemma_id_3 = self.mip.vocab.strings["draw a line in the sand"]

        self.assertIn(lemma_id_1, lemma_ids_1)
        self.assertIn(lemma_id_2, lemma_ids_2)
        self.assertIn(lemma_id_3, lemma_ids_3)
```

**Comment by eubinecto** [comment]
## well it turned out..

there was no problem with the code. haha. But it's great that you have written tests for that!
