### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/merge-idioms#3]
> 10th of Jan 2021

## To-do's
- [ ] ~(optional) `is_idiom` custom attribute~ better to assign it with an Entity value.
- [x] refactoring loaders: loaders just get the path directly from config. 조삼모사.
- [ ] project root settings - `setup.py` should be in the project root. not the library. `slide` folder should go back to `merge-idioms` directory. `merge_Idioms` directory is what gets distributed. So...we need the vocabulary. learn from the project structure of `spaCy`.
- [x] new script: save target idioms.
- [ ] save vocabulary separately -> something to think about? You shouldn't be building it every single time.. 아, 이 문제는, 그냥 하나의 모델을 shipping 하면 끝남. 아닌가? vocabulary가 달라질 수 있다는 것이 문제. 매번 동일한 것을.. 더하고 있으니. 아니 근데... 사실 큰 문제가 아닐수도? 큰 문제 맞음. 그냥 hash함수를 씀. 다른 환경으로 옮겨 졌을 때, 각 idiom이 어떤 값을 얻을지 모른다. 그게 문제.
